name: Node CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*'
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [12.16.1]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: mkdir sashimi-frontend
    - run: yarn
    - run: npm run pkg:online
      env:
        CI: true
    - run: cp build-online.tar.gz sashimi-frontend/
#     - run: npm run pkg:online-test
#       env:
#         CI: true
#     - run: cp build-online-test.tar.gz sashimi-frontend/
#     - run: npm run pkg:kovan
#       env:
#         CI: true
#     - run: cp build-kovan.tar.gz sashimi-frontend/
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: ./sashimi-frontend/build-online.tar.gz
        asset_name: build-online.tar.gz
        asset_content_type: application/gz
	
